from fastapi import APIRouter, HTTPException, Query
from typing import Optional
import hashlib
import time
import pandas as pd
from pathlib import Path

from app.services.projection_service import get_projection_service
from app.models.schemas import ProjectionResponse
from app.utils.logger import get_logger

router = APIRouter()
logger = get_logger(__name__)

# Simple in-memory cache with TTL
_projection_cache = {}
_projection_cache_ttl = 600  # 10 minutes


def get_cache_key(ncaa_id, current_year, years_ahead, min_samples):
    """Generate cache key for projection requests."""
    key_str = f"{ncaa_id}_{current_year}_{years_ahead}_{min_samples}"
    return hashlib.md5(key_str.encode()).hexdigest()


@router.get("/players/{ncaa_id}/projections", response_model=ProjectionResponse)
def get_player_projections(
    ncaa_id: str,
    current_year: Optional[int] = Query(default=2026, ge=2019, le=2030, description="Current year for the player"),
    years_ahead: int = Query(default=1, ge=1, le=3, description="Number of years to project (1-3)"),
    min_samples: int = Query(default=10, ge=5, le=100, description="Minimum historical samples required")
):
    """
    Get cluster-based BPM projections for a player.
    
    This endpoint uses historical year-over-year BPM changes from players
    in the same cluster to predict a target player's growth, weighted by
    feature similarity.
    
    Args:
        ncaa_id: Player NCAA ID
        current_year: Current year for the player (default: 2026)
        years_ahead: Number of years to project (1-3, default: 1)
        min_samples: Minimum historical samples required (5-100, default: 10)
    
    Returns:
        ProjectionResponse with projected BPM, confidence intervals, and similar players
    """
    try:
        # Check cache
        cache_key = get_cache_key(ncaa_id, current_year, years_ahead, min_samples)
        cached_data, cached_time = _projection_cache.get(cache_key, (None, 0))
        
        if cached_data and (time.time() - cached_time) < _projection_cache_ttl:
            logger.info(f"Returning cached projection for player {ncaa_id}")
            return cached_data
        
        # Get projection service
        service = get_projection_service()
        
        # Calculate projection
        result = service.calculate_projection(
            ncaa_id=ncaa_id,
            current_year=current_year,
            years_ahead=years_ahead,
            min_samples=min_samples
        )
        
        # Check for errors
        if 'error' in result:
            logger.warning(f"Projection error for player {ncaa_id}: {result['error']}")
            raise HTTPException(status_code=404, detail=result['error'])
        
        # Convert to response model
        response = ProjectionResponse(**result)
        
        # Store in cache
        _projection_cache[cache_key] = (response, time.time())
        
        logger.info(f"Generated projection for player {ncaa_id} (cluster {result['cluster_id']}, {result['historical_samples']} samples)")
        
        return response
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Unexpected error in projection endpoint: {str(e)}")
        raise HTTPException(status_code=500, detail="Internal server error")


@router.get("/projections/leaderboard")
def get_projections_leaderboard(
    sort_by: str = Query(default="projected_bpm", description="Sort by: projected_bpm, bpm_change, current_bpm"),
    order: str = Query(default="desc", description="Order: asc or desc"),
    limit: int = Query(default=100, ge=1, le=500, description="Number of results to return"),
    offset: int = Query(default=0, ge=0, description="Offset for pagination")
):
    """
    Get 2027 BPM projection leaderboard.
    
    This endpoint reads from a pre-calculated CSV file generated by the
    generate_projection_leaderboard.py script, ensuring consistency with
    the individual player projection endpoint while providing fast response times.
    
    Args:
        sort_by: Field to sort by (projected_bpm, bpm_change, current_bpm)
        order: Sort order (asc or desc)
        limit: Number of results to return (1-500)
        offset: Offset for pagination
    
    Returns:
        List of players with their 2027 projections sorted by the specified field
    """
    try:
        # Load the pre-calculated projections CSV file
        projections_file = Path(__file__).parent.parent.parent / "data" / "projection_leaderboard_2027.csv"
        
        if not projections_file.exists():
            raise HTTPException(status_code=404, detail="Projections leaderboard data not found. Run generate_projection_leaderboard.py to generate it.")
        
        df = pd.read_csv(projections_file)
        
        # Validate sort_by parameter
        valid_sort_fields = ['projected_bpm', 'bpm_change', 'current_bpm']
        if sort_by not in valid_sort_fields:
            raise HTTPException(status_code=400, detail=f"Invalid sort_by. Must be one of: {valid_sort_fields}")
        
        # Validate order parameter
        if order not in ['asc', 'desc']:
            raise HTTPException(status_code=400, detail="Order must be 'asc' or 'desc'")
        
        # Sort the dataframe
        ascending = order == 'asc'
        df_sorted = df.sort_values(by=sort_by, ascending=ascending)
        
        # Apply pagination
        total_count = len(df_sorted)
        df_paginated = df_sorted.iloc[offset:offset + limit]
        
        # Convert to list of dictionaries
        results = df_paginated.to_dict('records')
        
        # Format the results
        formatted_results = []
        for row in results:
            formatted_results.append({
                'player_key': str(row.get('player_key', '')),
                'player_name': row.get('player_name', ''),
                'team': row.get('team', ''),
                'current_bpm': float(row.get('current_bpm', 0)) if pd.notna(row.get('current_bpm')) else None,
                'bpm_change_predicted': float(row.get('bpm_change_predicted', 0)) if pd.notna(row.get('bpm_change_predicted')) else None,
                'projected_bpm': float(row.get('projected_bpm', 0)) if pd.notna(row.get('projected_bpm')) else None,
                'projected_bpm_lower_90': float(row.get('projected_bpm_lower_90', 0)) if pd.notna(row.get('projected_bpm_lower_90')) else None,
                'projected_bpm_upper_90': float(row.get('projected_bpm_upper_90', 0)) if pd.notna(row.get('projected_bpm_upper_90')) else None,
                'ncaa_id': str(row.get('player_key', ''))
            })
        
        return {
            'success': True,
            'count': len(formatted_results),
            'total_count': total_count,
            'offset': offset,
            'limit': limit,
            'sort_by': sort_by,
            'order': order,
            'results': formatted_results
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error in projections leaderboard: {str(e)}")
        raise HTTPException(status_code=500, detail="Internal server error")


@router.get("/clusters/{cluster_id}/projections-summary")
def get_cluster_projections_summary(
    cluster_id: int,
    limit: int = Query(default=10, ge=1, le=50)
):
    """
    Get a summary of projection statistics for a specific cluster.
    
    Args:
        cluster_id: Cluster ID to analyze
        limit: Number of top players to return (default: 10)
    
    Returns:
        Summary of projection statistics for the cluster
    """
    try:
        service = get_projection_service()
        
        # Get historical data for this cluster
        historical_data = service.get_cluster_historical_data(cluster_id)
        
        if historical_data.empty:
            raise HTTPException(status_code=404, detail=f"No data found for cluster {cluster_id}")
        
        # Calculate summary statistics
        bpm_changes = historical_data['bpm_change'].dropna()
        
        summary = {
            'cluster_id': cluster_id,
            'total_samples': len(historical_data),
            'valid_bpm_changes': len(bpm_changes),
            'avg_bpm_change': float(bpm_changes.mean()) if len(bpm_changes) > 0 else None,
            'median_bpm_change': float(bpm_changes.median()) if len(bpm_changes) > 0 else None,
            'std_bpm_change': float(bpm_changes.std()) if len(bpm_changes) > 0 else None,
            'positive_changes': int((bpm_changes > 0).sum()) if len(bpm_changes) > 0 else 0,
            'negative_changes': int((bpm_changes < 0).sum()) if len(bpm_changes) > 0 else 0,
        }
        
        # Get top positive and negative changes
        if len(bpm_changes) > 0:
            top_positive = historical_data.nlargest(limit, 'bpm_change')[['player_key', 'year_from', 'year_to', 'bpm_change']].to_dict('records')
            top_negative = historical_data.nsmallest(limit, 'bpm_change')[['player_key', 'year_from', 'year_to', 'bpm_change']].to_dict('records')
            
            summary['top_improvements'] = [
                {
                    'player_key': row['player_key'],
                    'year_from': int(row['year_from']),
                    'year_to': int(row['year_to']),
                    'bpm_change': float(row['bpm_change'])
                }
                for row in top_positive
            ]
            summary['top_declines'] = [
                {
                    'player_key': row['player_key'],
                    'year_from': int(row['year_from']),
                    'year_to': int(row['year_to']),
                    'bpm_change': float(row['bpm_change'])
                }
                for row in top_negative
            ]
        
        return summary
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error in cluster projections summary: {str(e)}")
        raise HTTPException(status_code=500, detail="Internal server error")
